### PR TITLE
Fix a grammatical error.  Default to CPU as the processor.  Etc.

### PR DESCRIPTION
**Pull request by andborth**
Fix a grammatical error.  Default to CPU as the processor.  Execute all code

### CODE REVIEW

**Comment by zackchase** [comment]
Actually it's better to not execute the cells. They are executed
automatically by the build process for mxnet.io.

**Comment by zackchase** [comment]
If you execute the cells then it muddies the repo (outputs count as code
for GitHub)

Z

**Comment by andborth** [comment]
Okay.  I'll leave the cells unexecuted going forward for my pull requests.  

It seems like the book is really inconsistent on whether the cells are executed or not right now.  They aren't currently executed on this page, for instance:  http://gluon.mxnet.io/chapter03_deep-neural-networks/mlp-dropout-gluon.html

**Comment by zackchase** [comment]
Please on execute the cells before I merge this PR

**Comment by andborth** [comment]
Closed in favor of pull request #453

**Pull request closed without merging**
