### PR TITLE
Add context scope for pytorch and 1.4 `cross device` and 2 `autograd`

### PR DESCRIPTION
**Pull request by ZiyueHuang**
Pytorch also has a context manager `torch.cuda.device(dev_id)` as described in http://pytorch.org/docs/master/notes/cuda.html.

Add section 1.4 `cross device`.

cc @szha

### CODE REVIEW

**Comment by zackchase** [comment]
@szha thoughts?

**Comment by szha** [comment]
Looks good!

**Comment by ZiyueHuang** [comment]
I remove 2.2 `gluon can supply head grad` because it is very similar in pytorch/gluon to supply head  grads, e.g, `y.backward(out_grad)` or using `autograd.grad(...)`.

Is this section neccessary? @szha

**Comment by szha** [comment]
@ZiyueHuang you can decide to make sure it's coherent, since you picked the whole section :)
BTW Zack mentioned that the repo is being re-organized for CI, so he's holding onto the PRs for now. No worries.

**Comment by zackchase** [comment]
Hi @ZiyueHuang  @szha - it seems that the conversion is more complicated than expected (as should be expected (meta-expected?)). so I'll resume merging until Mu is sure we're ready to convert over.

**Pull request merged**
