### PR TITLE
fix hacks in finetuning example

### PR DESCRIPTION
**Pull request by szha**

### CODE REVIEW

**Comment by szha** [comment]
Fixes #178. Needs apache/incubator-mxnet#7667 to work.

**Comment by zackchase** [comment]
Thanks @szha !

**Comment by szha** [comment]
apache/incubator-mxnet#7667 is not merged yet. Next time, if there's new mxnet feature needed, let's wait for the dependency to be merged first, and then wait a day for the nightly build, before merging such change.

**Comment by zackchase** [comment]
Yep. I realized after the fact. Agreed.

**Pull request merged**
