### PR TITLE
Minor correction on notation in vector dot product

### PR DESCRIPTION
**Pull request by dingran**
@astonzhang

### CODE REVIEW

**Comment by zackchase** [comment]
@astonzhang -- you are the owner of this notebook atm - please review this PR

**Comment by astonzhang** [comment]
i reviewed, but switching x \dot y to y \dot x doesn't seem different

**Comment by dingran** [comment]
hi @astonzhang, I was thinking in this notebook all vectors are column vectors unless otherwise noted, so it actually should be u^T dot nabla_f. Anyways, for numpy stuff it doesn't make any difference, as you said, just a minor notation detail. Feel free to close this

**Comment by astonzhang** [comment]
@dingran Thanks. dot product operator is different from multiplication operator. x \cdot y <=> x^T y.

**Comment by astonzhang** [comment]
I'm going to close this. You are more than welcome to send other PRs in the future :)

**Pull request closed without merging**
