### PR TITLE
first draft intro forecasting with gluon

### PR DESCRIPTION
**Pull request by lcallot**
First draft of intro to forecasting in gluon. I use a linear model with L2 loss throughout

 
 1. Using deterministic features
   - trend
   - seasonal
2. Stochastic features
  - Autoregressive model
  - Forecast confidence intervals: analytical and simulation based.

### CODE REVIEW

**Comment by zackchase** [comment]
This looks good -- sorry for long delay. I'm going to go through tomorrow slowly and think about best way to integrate to current time series TOC. Thanks for the contrib!

**Comment by lcallot** [comment]
@zackchase Any chance you can take a look at this and let me know what I can do to make it integrate well withing the time series chapter?

**Comment by zackchase** [comment]
Sorry for the delay during the move to PA. Thanks for the notebook! I'm merging now and looking forward to see where you and Bernie take it next.

**Comment by lovvge** [comment]
Thanks, Zack!

**Pull request merged**
