### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by simoncorstonoliver**
A few tiny fixes.

Unclear if you prefer to have the output of the notebooks cleared out or not. I cleared it so it was only text and code but no output.

### CODE REVIEW

**Comment by zackchase** [comment]
Yeah we're moving to clear the output. This way matplotlib graphs don't show up as part of the source code :)

**Comment by zackchase** [comment]
Please resolve conflicts so I can merge.

**Comment by simoncorstonoliver** [comment]
Conflicts resolved.

**Comment by zackchase** [comment]
Thanks!

**Pull request merged**
