### PR TITLE
Add dcgan

### PR DESCRIPTION
**Pull request by kevinthesun**
Add dcgan tutorial.

### CODE REVIEW

**Comment by piiswrong** [comment]
Training loop is too complicated. We don't need multi-gpu for dcgan tutorial.

See the dcgan example in example/gluon

**Comment by zackchase** [comment]
Good point @piiswrong. @kevininthesun, would you mind simplifying the training loop?

**Comment by kevinthesun** [comment]
sure.

**Comment by zackchase** [comment]
This is an awesome draft and clear readable example code. I'll make a pass to add some more writing later and merge now. Thanks Yao! Looking forward to the next contributions! :)

**Pull request merged**
