### PR TITLE
Adding chapter on Graph Neural Networks

### PR DESCRIPTION
**Pull request by mwcvitkovic**
As requested by Anima.  @szha, @aaronmarkham asked me to ask you (and him) to review it.  Cheers!

### CODE REVIEW

**Comment by szha** [comment]
cc @sxjscience

**Comment by zackchase** [comment]
Thanks I'll read through soon!

**Comment by zackchase** [comment]
Looks good! Merging now and will try to make some time to go through and work on integration with the rest of the book.

**Comment by zackchase** [comment]
I generally try to avoid dependencies but perhaps it's unavoidable here? We might have an issue if we try to include it in the html build because it won't pass tests if the dependencies aren't on the testing server. @mli what do you think?

**Comment by mwcvitkovic** [comment]
Yeah I'm unhappy about the dependencies.  I really tried to avoid them, but interesting, fairly simple, small-input-size graph data with an API is hard to find.  If you come across an easier-to-use dataset I'm happy to switch the chapter to use it.

**Comment by aaronmarkham** [comment]
Should we add this to the main readme, so it shows up in the ToC?

**Comment by mwcvitkovic** [comment]
Totally missed this @aaronmarkham, sorry.  What do I have to do to add the chapter to the ToC?

**Comment by aaronmarkham** [comment]
Edit the readme in the root, and somehow get the site to rebuild. I think Zack might have to trigger the build but at least get this in the index.

**Pull request merged**
