### PR TITLE
Add SGD with momentum

### PR DESCRIPTION
**Pull request by astonzhang**
The two figures are self-made without copyright issues.

### CODE REVIEW

**Comment by astonzhang** [comment]
Preview at:
https://github.com/astonzhang/mxnet-the-straight-dope/blob/master/chapter06_optimization/sgd-momentum.ipynb

**Comment by piiswrong** [comment]
Can we get some real examples? Something like this https://www.oreilly.com/ideas/contouring-learning-rate-to-optimize-neural-nets

**Comment by astonzhang** [comment]
Thanks Eric! I'll take a look.

**Comment by zackchase** [comment]
I merged but please continue to improve and follow up on Eric's idea

**Pull request merged**
